import type { SquadPlayer } from './tournament'

// Elencos da temporada 2026/27 (25/26 ja encerrada), compilados a partir de
// Wikipedia, sites oficiais dos clubes e BeSoccer em 20/08/2026. Sem numero
// oficial de camisa para alguns jovens/reservas (number: null). Sem fotos.
export const defaultSquads: Record<string, SquadPlayer[]> = {
  capflint: [
    { id: 1, name: 'Manuel Neuer', number: 1, position: 'GK', photo: '' },
    { id: 2, name: 'Dayot Upamecano', number: 2, position: 'DF', photo: '' },
    { id: 3, name: 'Kim Min-jae', number: 3, position: 'DF', photo: '' },
    { id: 4, name: 'Jonathan Tah', number: 4, position: 'DF', photo: '' },
    { id: 5, name: 'Joshua Kimmich', number: 6, position: 'MF', photo: '' },
    { id: 6, name: 'Serge Gnabry', number: 7, position: 'FW', photo: '' },
    { id: 7, name: 'Leon Goretzka', number: 8, position: 'MF', photo: '' },
    { id: 8, name: 'Harry Kane', number: 9, position: 'FW', photo: '' },
    { id: 9, name: 'Jamal Musiala', number: 10, position: 'MF', photo: '' },
    { id: 10, name: 'Nicolas Jackson', number: 11, position: 'FW', photo: '' },
    { id: 11, name: 'Luis Diaz', number: 14, position: 'FW', photo: '' },
    { id: 12, name: 'Michael Olise', number: 17, position: 'FW', photo: '' },
    { id: 13, name: 'Alphonso Davies', number: 19, position: 'DF', photo: '' },
    { id: 14, name: 'Tom Bischof', number: 20, position: 'MF', photo: '' },
    { id: 15, name: 'Hiroki Ito', number: 21, position: 'DF', photo: '' },
    { id: 16, name: 'Raphael Guerreiro', number: 22, position: 'DF', photo: '' },
    { id: 17, name: 'Sven Ulreich', number: 26, position: 'GK', photo: '' },
    { id: 18, name: 'Konrad Laimer', number: 27, position: 'MF', photo: '' },
    { id: 19, name: 'Cassiano Kiala', number: 30, position: 'DF', photo: '' },
    { id: 20, name: 'Wisdom Mike', number: 36, position: 'FW', photo: '' },
    { id: 21, name: 'Jonas Urbig', number: 40, position: 'GK', photo: '' },
    { id: 22, name: 'Lennart Karl', number: 42, position: 'MF', photo: '' },
    { id: 23, name: 'Josip Stanisic', number: 44, position: 'DF', photo: '' },
    { id: 24, name: 'Aleksandar Pavlovic', number: 45, position: 'MF', photo: '' },
    { id: 25, name: 'David Santos Daiber', number: 47, position: 'MF', photo: '' },
    { id: 26, name: 'Leon Klanac', number: 48, position: 'GK', photo: '' },
  ],
  falcon: [
    { id: 1, name: 'Lucas Chevalier', number: 30, position: 'GK', photo: '' },
    { id: 2, name: 'Matvey Safonov', number: 39, position: 'GK', photo: '' },
    { id: 3, name: 'Renato Marin', number: 89, position: 'GK', photo: '' },
    { id: 4, name: 'Achraf Hakimi', number: 2, position: 'DF', photo: '' },
    { id: 5, name: 'Lucas Beraldo', number: 4, position: 'DF', photo: '' },
    { id: 6, name: 'Marquinhos', number: 5, position: 'DF', photo: '' },
    { id: 7, name: 'Illia Zabarnyi', number: 6, position: 'DF', photo: '' },
    { id: 8, name: 'Lucas Hernandez', number: 21, position: 'DF', photo: '' },
    { id: 9, name: 'Nuno Mendes', number: 25, position: 'DF', photo: '' },
    { id: 10, name: 'Willian Pacho', number: 51, position: 'DF', photo: '' },
    { id: 11, name: 'Fabian Ruiz', number: 8, position: 'MF', photo: '' },
    { id: 12, name: 'Vitinha', number: 17, position: 'MF', photo: '' },
    { id: 13, name: 'Lee Kang-in', number: 19, position: 'MF', photo: '' },
    { id: 14, name: 'Senny Mayulu', number: 24, position: 'MF', photo: '' },
    { id: 15, name: 'Ibrahim Mbaye', number: 27, position: 'MF', photo: '' },
    { id: 16, name: 'Warren Zaire-Emery', number: 33, position: 'MF', photo: '' },
    { id: 17, name: 'Joao Neves', number: 87, position: 'MF', photo: '' },
    { id: 18, name: 'Khvicha Kvaratskhelia', number: 7, position: 'FW', photo: '' },
    { id: 19, name: 'Goncalo Ramos', number: 9, position: 'FW', photo: '' },
    { id: 20, name: 'Ousmane Dembele', number: 10, position: 'FW', photo: '' },
    { id: 21, name: 'Desire Doue', number: 14, position: 'FW', photo: '' },
    { id: 22, name: 'Bradley Barcola', number: 29, position: 'FW', photo: '' },
    { id: 23, name: 'Quentin Ndjantou', number: 47, position: 'FW', photo: '' },
  ],
  leo: [
    { id: 1, name: 'Thibaut Courtois', number: 1, position: 'GK', photo: '' },
    { id: 2, name: 'Andriy Lunin', number: 13, position: 'GK', photo: '' },
    { id: 3, name: 'Denzel Dumfries', number: 24, position: 'DF', photo: '' },
    { id: 4, name: 'Dean Huijsen', number: 4, position: 'DF', photo: '' },
    { id: 5, name: 'Ibrahima Konate', number: 16, position: 'DF', photo: '' },
    { id: 6, name: 'Antonio Rudiger', number: 22, position: 'DF', photo: '' },
    { id: 7, name: 'Trent Alexander-Arnold', number: 12, position: 'DF', photo: '' },
    { id: 8, name: 'Marc Cucurella', number: 17, position: 'DF', photo: '' },
    { id: 9, name: 'Alvaro Carreras', number: 18, position: 'DF', photo: '' },
    { id: 10, name: 'Eder Militao', number: 3, position: 'DF', photo: '' },
    { id: 11, name: 'Raul Asencio', number: 2, position: 'DF', photo: '' },
    { id: 12, name: 'Ferland Mendy', number: 23, position: 'DF', photo: '' },
    { id: 13, name: 'Federico Valverde', number: 8, position: 'MF', photo: '' },
    { id: 14, name: 'Jude Bellingham', number: 5, position: 'MF', photo: '' },
    { id: 15, name: 'Bernardo Silva', number: 20, position: 'MF', photo: '' },
    { id: 16, name: 'Aurelien Tchouameni', number: 14, position: 'MF', photo: '' },
    { id: 17, name: 'Arda Guler', number: 15, position: 'MF', photo: '' },
    { id: 18, name: 'Eduardo Camavinga', number: 6, position: 'MF', photo: '' },
    { id: 19, name: 'Thiago Pitarch', number: 27, position: 'MF', photo: '' },
    { id: 20, name: 'Kylian Mbappe', number: 10, position: 'FW', photo: '' },
    { id: 21, name: 'Vinicius Junior', number: 7, position: 'FW', photo: '' },
    { id: 22, name: 'Rodrygo', number: 11, position: 'FW', photo: '' },
    { id: 23, name: 'Endrick', number: 9, position: 'FW', photo: '' },
    { id: 24, name: 'Brahim Diaz', number: 21, position: 'FW', photo: '' },
    { id: 25, name: 'Yasser Diomande', number: 25, position: 'FW', photo: '' },
    { id: 26, name: 'Carlos Espi', number: 19, position: 'FW', photo: '' },
  ],
  manduca: [
    { id: 1, name: 'Josep Martinez', number: 1, position: 'GK', photo: '' },
    { id: 2, name: 'Raffaele Di Gennaro', number: 12, position: 'GK', photo: '' },
    { id: 3, name: 'Ivan Provedel', number: 49, position: 'GK', photo: '' },
    { id: 4, name: 'Federico Dimarco', number: 32, position: 'DF', photo: '' },
    { id: 5, name: 'Alessandro Bastoni', number: 95, position: 'DF', photo: '' },
    { id: 6, name: 'Manuel Akanji', number: 25, position: 'DF', photo: '' },
    { id: 7, name: 'Benjamin Pavard', number: 28, position: 'DF', photo: '' },
    { id: 8, name: 'Carlos Augusto', number: 30, position: 'DF', photo: '' },
    { id: 9, name: 'Djed Spence', number: null, position: 'DF', photo: '' },
    { id: 10, name: 'Yann Bisseck', number: 31, position: 'DF', photo: '' },
    { id: 11, name: 'John Stones', number: 6, position: 'DF', photo: '' },
    { id: 12, name: 'Nicolo Barella', number: 23, position: 'MF', photo: '' },
    { id: 13, name: 'Hakan Calhanoglu', number: 20, position: 'MF', photo: '' },
    { id: 14, name: 'Piotr Zielinski', number: 7, position: 'MF', photo: '' },
    { id: 15, name: 'Aleksandar Stankovic', number: 5, position: 'MF', photo: '' },
    { id: 16, name: 'Henrikh Mkhitaryan', number: 22, position: 'MF', photo: '' },
    { id: 17, name: 'Luis Henrique', number: 11, position: 'MF', photo: '' },
    { id: 18, name: 'Kristjan Asllani', number: null, position: 'MF', photo: '' },
    { id: 19, name: 'Petar Sucic', number: 8, position: 'MF', photo: '' },
    { id: 20, name: 'Andy Diouf', number: 17, position: 'MF', photo: '' },
    { id: 21, name: 'Yaw Massolin', number: null, position: 'MF', photo: '' },
    { id: 22, name: 'Lautaro Martinez', number: 10, position: 'FW', photo: '' },
    { id: 23, name: 'Marcus Thuram', number: 9, position: 'FW', photo: '' },
    { id: 24, name: 'Pio Esposito', number: 94, position: 'FW', photo: '' },
    { id: 25, name: 'Ange-Yoan Bonny', number: 14, position: 'FW', photo: '' },
  ],
  nsb: [
    { id: 1, name: 'Joan Garcia', number: 1, position: 'GK', photo: '' },
    { id: 2, name: 'Wojciech Szczesny', number: 13, position: 'GK', photo: '' },
    { id: 3, name: 'Diego Yaakobishvili', number: null, position: 'GK', photo: '' },
    { id: 4, name: 'Jules Kounde', number: 23, position: 'DF', photo: '' },
    { id: 5, name: 'Alejandro Balde', number: 3, position: 'DF', photo: '' },
    { id: 6, name: 'Pau Cubarsi', number: 5, position: 'DF', photo: '' },
    { id: 7, name: 'Eric Garcia', number: 24, position: 'DF', photo: '' },
    { id: 8, name: 'Andreas Christensen', number: 15, position: 'DF', photo: '' },
    { id: 9, name: 'Gerard Martin', number: 18, position: 'DF', photo: '' },
    { id: 10, name: 'Hector Fort', number: null, position: 'DF', photo: '' },
    { id: 11, name: 'Alex Cortes', number: null, position: 'DF', photo: '' },
    { id: 12, name: 'Xavi Espart', number: null, position: 'DF', photo: '' },
    { id: 13, name: 'Rodri', number: 16, position: 'MF', photo: '' },
    { id: 14, name: 'Pedri', number: 8, position: 'MF', photo: '' },
    { id: 15, name: 'Frenkie de Jong', number: 21, position: 'MF', photo: '' },
    { id: 16, name: 'Dani Olmo', number: 20, position: 'MF', photo: '' },
    { id: 17, name: 'Fermin Lopez', number: 7, position: 'MF', photo: '' },
    { id: 18, name: 'Gavi', number: 6, position: 'MF', photo: '' },
    { id: 19, name: 'Marc Casado', number: 17, position: 'MF', photo: '' },
    { id: 20, name: 'Marc Bernal', number: 22, position: 'MF', photo: '' },
    { id: 21, name: 'Toni Fernandez', number: null, position: 'MF', photo: '' },
    { id: 22, name: 'Bernat Farinas', number: null, position: 'MF', photo: '' },
    { id: 23, name: 'Tommy Marques', number: null, position: 'MF', photo: '' },
    { id: 24, name: 'Lamine Yamal', number: 10, position: 'FW', photo: '' },
    { id: 25, name: 'Raphinha', number: 11, position: 'FW', photo: '' },
    { id: 26, name: 'Anthony Gordon', number: 25, position: 'FW', photo: '' },
    { id: 27, name: 'Karim Adeyemi', number: 14, position: 'FW', photo: '' },
    { id: 28, name: 'Roony Bardghji', number: 19, position: 'FW', photo: '' },
    { id: 29, name: 'Jesse Bisiwu', number: 27, position: 'FW', photo: '' },
  ],
}
